name: CI/CD with GCP Compute Engine

on:
    push:
        branches: [production]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node Environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11.1

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: milaymaxell/upcsg:latest
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Decode and Write SSH key to file
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.PRIVATE_SSH_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

            - name: Add SSH key to the SSH agent
              run: |
                  eval $(ssh-agent -s)
                  ssh-add ~/.ssh/id_rsa

            - name: Configure SSH
              run: |
                  ssh-keyscan github.com >> ~/.ssh/known_hosts

            - name: SSH into Deployment Server
              run: ssh -i ~/.ssh/id_rsa ${{ secrets.REMOTE_SERVER_USER }}:${{ secrets.EXTERNAL_IP_ADDRESS }}

            - name: Pull Docker Image
              run: docker pull milaymaxell/upcsg:latest

            - name: Delete Old Docker Container
              run: docker rm -f ci-cd-pipeline-container || true

            - name: Run Docker Container
              run: docker run -d -p 3000:3000 --name ci-cd-pipeline-container milaymaxell/upcsg
