name: CI/CD with GCP Compute Engine

on:
    push:
        branches: [production]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node Environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11.1

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: milaymaxell/upcsg:latest
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}

            - name: Add server to known hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -H ${{ secrets.EXTERNAL_IP_ADDRESS }} >> ~/.ssh/known_hosts

            - name: SSH into Deployment Server
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USER }}@${{ secrets.EXTERNAL_IP_ADDRESS }} << 'EOF'
                    docker pull milaymaxell/upcsg
                    CONTAINER_IDS=$(docker ps -aq)
                    if [ ! -z "$CONTAINER_IDS" ]; then
                      docker stop $CONTAINER_IDS
                      docker rm $CONTAINER_IDS
                    fi
                    docker run -d -p 3000:3000 milaymaxell/upcsg:latest
                  EOF
